#!/usr/bin/env node
/**
 * entity-setup.js
 * Interactive first-run setup for Entity workspace.
 * Generates entity.config.yaml from user prompts with safe local defaults.
 */
const fs = require('fs');
const path = require('path');
const readline = require('readline');

const CONFIG_DIR = path.join(__dirname, '..');
const CONFIG_PATH = path.join(CONFIG_DIR, 'entity.config.yaml');
const ENV_PATH = path.join(CONFIG_DIR, '.env');

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });

function ask(question) {
  return new Promise(resolve => rl.question(question, resolve));
}

function askDefault(question, defaultVal) {
  return new Promise(resolve => {
    rl.question(`${question} [${defaultVal}]: `, answer => {
      resolve(answer.trim() || defaultVal);
    });
  });
}

async function main() {
  console.log('');
  console.log('Entity Workspace Setup');
  console.log('======================');
  console.log('This will create a safe local-first configuration.');
  console.log('');

  const displayName = await askDefault('Display name for this workspace', 'My Entity Workspace');
  const ownerName = await askDefault('Owner/user display name', 'Local User');
  const serverPort = await askDefault('Server port', '3000');
  const workspaceRoot = await askDefault('Workspace root path', '~/entity-workspace');

  const useOnboarding = (await askDefault('Run first-run onboarding wizard (y/n)', 'n')).toLowerCase() === 'y';

  const yaml = [
    '# Entity Configuration',
    '# Generated by npm run setup',
    '',
    'version: 1',
    '',
    `profile:`,
    `  displayName: ${JSON.stringify(displayName)}`,
    `  ownerName: ${JSON.stringify(ownerName)}`,
    '',
    'server:',
    `  host: localhost`,
    `  port: ${serverPort}`,
    `  workspaceRoot: ${JSON.stringify(workspaceRoot)}`,
    `  publicBaseUrl: "http://localhost:${serverPort}"`,
    `  apiBaseUrl: "http://localhost:${serverPort}"`,
    `  wsBaseUrl: "ws://localhost:${serverPort}"`,
    `  databasePath: "./data/entity.sqlite"`,
    `  logPath: "./logs/entity.log"`,
    '',
    'agents:',
    '  - id: assistant',
    '    name: Assistant',
    '    emoji: "🤖"',
    '    enabled: true',
    '    role: general',
    '    fileSources: []',
    '    gateway:',
    '      type: none',
    '      url: null',
    '      tokenRef: null',
    '',
    'fileSources: []',
    '',
    'services: []',
    '',
    'providers: {}',
    'plugins: {}',
    'voice:',
    '  defaultProvider: browser',
    '  providers: {}',
    'deploy:',
    '  mode: local',
    '  preserveDatabase: true',
    '  dryRunByDefault: true',
    'terminal:',
    '  targets: []',
  ].filter(line => line !== '').join('\n');

  fs.writeFileSync(CONFIG_PATH, yaml);

  // Create .env if it doesn't exist
  if (!fs.existsSync(ENV_PATH)) {
    const envContent = [
      '# Entity Environment Configuration',
      '# Generated by npm run setup - safe local defaults',
      '',
      'ENTITY_CONFIG=entity.config.yaml',
      'ENTITY_DB_MODE=LOCAL',
      `ENTITY_CLOUD_API_BASE=http://localhost:${serverPort}`,
      `VITE_MC_ORIGIN=http://localhost:${serverPort}`,
      `VITE_ENTITY_API_BASE=http://localhost:${serverPort}`,
      'ENTITY_FS_MULTISOURCE=true',
      'ENTITY_FS_INDEXER_ENABLED=false',
      `PORT=${serverPort}`,
      'ENTITY_API_TOKEN=',
      'ENTITY_DEFAULT_DOCUMENTS_TOKEN=',
      '',
    ].join('\n');
    fs.writeFileSync(ENV_PATH, envContent);
  }

  console.log('');
  console.log('Configuration created:');
  console.log(`  entity.config.yaml (${CONFIG_PATH})`);
  console.log(`  .env (${ENV_PATH})`);
  console.log('');
  console.log('Next steps:');
  console.log('  npm run build      # Build all packages');
  console.log('  npm run dev        # Start development server');
  console.log('  npm run doctor     # Check workspace health');
  console.log('');

  if (useOnboarding) {
    console.log('Onboarding: visit http://localhost:' + serverPort + '/onboarding');
  }

  rl.close();
}

main().catch(e => { console.error(e); process.exit(1); });