#!/bin/bash
# Entity Context Auto-Update Script
# Run after every build to regenerate context files from actual source
# Usage: ./scripts/update-context.sh
#
# Canonical context location: memory/projects/entity/
# Web-accessible copy: docs/

set -e

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

echo "🔄 Updating Entity context files..."
echo "   Repo: $REPO_ROOT"
echo "   Canonical: memory/projects/entity/"
echo "   Web copy: docs/"

# Ensure directories exist
mkdir -p memory/projects/entity docs scripts

NOW="$(date -u +"%Y-%m-%d %H:%M:%S UTC")"

# Count files in packages/
APP_TSX=$(find packages/app/src -name "*.tsx" 2>/dev/null | wc -l | tr -d ' ')
APP_TS=$(find packages/app/src -name "*.ts" 2>/dev/null | wc -l | tr -d ' ')
SERVER_TS=$(find packages/server/src -name "*.ts" 2>/dev/null | wc -l | tr -d ' ')
DB_TS=$(find packages/db/src -name "*.ts" 2>/dev/null | wc -l | tr -d ' ')

echo "📊 Stats: ${APP_TSX} tsx, ${APP_TS} ts (app), ${SERVER_TS} ts (server), ${DB_TS} ts (db)"

# ─── Update codemap.md with fresh file tree ─────────────────────────────────

cat > memory/projects/entity/codemap.md << HEADER
# Entity Codemap

> Auto-generated on ${NOW}

## Project Statistics

- **App TSX files:** ${APP_TSX}
- **App TS files:** ${APP_TS}
- **Server TS files:** ${SERVER_TS}
- **DB TS files:** ${DB_TS}

## packages/app/src/ (React Frontend)

### Components
HEADER

find packages/app/src/components -name "*.tsx" -o -name "*.ts" 2>/dev/null | sort >> memory/projects/entity/codemap.md || true

cat >> memory/projects/entity/codemap.md << 'SECTION'

### Hooks
SECTION
find packages/app/src/hooks -name "*.ts" -o -name "*.tsx" 2>/dev/null | sort >> memory/projects/entity/codemap.md || true

cat >> memory/projects/entity/codemap.md << 'SECTION'

### Types
SECTION
find packages/app/src/types -name "*.ts" 2>/dev/null | sort >> memory/projects/entity/codemap.md || true

cat >> memory/projects/entity/codemap.md << 'SECTION'

### Lib / Config
SECTION
find packages/app/src/lib packages/app/src/config -name "*.ts" 2>/dev/null | sort >> memory/projects/entity/codemap.md || true

cat >> memory/projects/entity/codemap.md << 'SECTION'

## packages/server/src/ (Express Backend)
SECTION
find packages/server/src -name "*.ts" 2>/dev/null | sort >> memory/projects/entity/codemap.md || true

cat >> memory/projects/entity/codemap.md << 'SECTION'

## packages/db/src/ (Database Layer)
SECTION
find packages/db/src -name "*.ts" 2>/dev/null | sort >> memory/projects/entity/codemap.md || true

cat >> memory/projects/entity/codemap.md << 'FOOTER'

---
_Auto-generated by scripts/update-context.sh_
FOOTER

echo "  ✅ memory/projects/entity/codemap.md"

# ─── Update timestamp in context.md ─────────────────────────────────────────
# context.md is manually maintained — only update the timestamp line

if [ -f memory/projects/entity/context.md ]; then
  # Replace the _Last updated_ line
  if grep -q "^_Last updated:" memory/projects/entity/context.md; then
    sed -i.bak "s|^_Last updated:.*|_Last updated: ${NOW}_|" memory/projects/entity/context.md && rm -f memory/projects/entity/context.md.bak
    echo "  ✅ memory/projects/entity/context.md (timestamp updated)"
  else
    echo "  ℹ️  memory/projects/entity/context.md (no timestamp line found — manual edit needed)"
  fi
else
  echo "  ⚠️  memory/projects/entity/context.md not found — create it manually"
fi

# ─── Copy memory/projects/entity/ → docs/ ────────────────────────────────────
cp memory/projects/entity/context.md docs/context.md 2>/dev/null && echo "  ✅ docs/context.md"
cp memory/projects/entity/codemap.md docs/codemap.md 2>/dev/null && echo "  ✅ docs/codemap.md"
cp memory/projects/entity/todo.md docs/todo.md 2>/dev/null && echo "  ✅ docs/todo.md"
cp memory/projects/entity/decisions.md docs/decisions.md 2>/dev/null && echo "  ✅ docs/decisions.md"
cp memory/projects/entity/timeline.md docs/timeline.md 2>/dev/null && echo "  ✅ docs/timeline.md"

# ─── Git commit if there are changes ────────────────────────────────────────
if [ -d .git ]; then
  git add memory/projects/entity/ docs/ scripts/update-context.sh 2>/dev/null || true
  if ! git diff --staged --quiet 2>/dev/null; then
    git commit -m "docs: auto-update context [$(date -u +%Y-%m-%d)]" 2>/dev/null || true
    echo "  ✅ Changes committed"
  else
    echo "  ℹ️  No changes to commit"
  fi
fi

echo ""
echo "✨ Done — context files updated at ${NOW}"
echo "   Canonical: memory/projects/entity/"
echo "   Web copy: docs/"
