#!/bin/bash
# update-entity-docs.sh - Update Entity project context docs after builds
# Run from entity repo root: ./scripts/update-docs.sh
# Or via Codex: codex exec "Run ./scripts/update-docs.sh"

set -e
REPO_ROOT="${1:-$(pwd)}"
DOCS="$REPO_ROOT/docs"

echo "📝 Updating Entity context docs..."
echo "Repo: $REPO_ROOT"
echo ""

# 1. Update codemap.md - file structure + key modules
echo "🗺️  Updating codemap.md..."
cat > "$DOCS/codemap.md" << 'HEADER'
# Entity Codemap

## File Structure
HEADER

# Tree of key directories (excluding node_modules, dist, .git)
echo '```' >> "$DOCS/codemap.md"
cd "$REPO_ROOT"
find packages/app/src packages/server/src packages/db/src -type f \( -name "*.ts" -o -name "*.tsx" -o -name "*.css" \) 2>/dev/null | sort >> "$DOCS/codemap.md"
echo '```' >> "$DOCS/codemap.md"

# Key components summary
cat >> "$DOCS/codemap.md" << 'SECTION'

## Key Components (packages/app/src/components/)
SECTION
ls -1 "$REPO_ROOT/packages/app/src/components/" 2>/dev/null | while read f; do
  echo "- \`$f\`" >> "$DOCS/codemap.md"
done

cat >> "$DOCS/codemap.md" << 'SECTION'

## Hooks (packages/app/src/hooks/)
SECTION
ls -1 "$REPO_ROOT/packages/app/src/hooks/" 2>/dev/null | while read f; do
  echo "- \`$f\`" >> "$DOCS/codemap.md"
done

cat >> "$DOCS/codemap.md" << 'SECTION'

## Server Routes (packages/server/src/)
SECTION
ls -1 "$REPO_ROOT/packages/server/src/" 2>/dev/null | while read f; do
  echo "- \`$f\`" >> "$DOCS/codemap.md"
done

echo "✅ codemap.md updated"

# 2. Update context.md - tech stack, dependencies, how to run
echo "📋 Updating context.md tech stack section..."
# Extract current dependencies
APP_DEPS=$(cd "$REPO_ROOT/packages/app" && node -e "const p=require('./package.json'); console.log(Object.keys(p.dependencies||{}).join(', '))" 2>/dev/null || echo "unknown")
SERVER_DEPS=$(cd "$REPO_ROOT/packages/server" && node -e "const p=require('./package.json'); console.log(Object.keys(p.dependencies||{}).join(', '))" 2>/dev/null || echo "unknown")

# Count components, hooks, lines
COMPONENT_COUNT=$(find "$REPO_ROOT/packages/app/src/components" -name "*.tsx" 2>/dev/null | wc -l | tr -d ' ')
HOOK_COUNT=$(find "$REPO_ROOT/packages/app/src/hooks" -name "*.ts" 2>/dev/null | wc -l | tr -d ' ')
TOTAL_TS_FILES=$(find "$REPO_ROOT/packages" -name "*.ts" -o -name "*.tsx" 2>/dev/null | grep -v node_modules | wc -l | tr -d ' ')
TOTAL_LINES=$(find "$REPO_ROOT/packages" \( -name "*.ts" -o -name "*.tsx" \) -not -path "*/node_modules/*" -exec cat {} + 2>/dev/null | wc -l | tr -d ' ')

# Get git info
LAST_COMMIT=$(cd "$REPO_ROOT" && git log --oneline -1 2>/dev/null || echo "unknown")
BRANCH=$(cd "$REPO_ROOT" && git branch --show-current 2>/dev/null || echo "unknown")

# Append stats to context.md (replace Stats section if exists, otherwise append)
STATS_MARKER="## Current Stats"
if grep -q "$STATS_MARKER" "$DOCS/context.md" 2>/dev/null; then
  # Remove old stats section (everything from marker to next ## or EOF)
  sed -i '' "/$STATS_MARKER/,/^## [^C]/{ /$STATS_MARKER/d; /^## [^C]/!d; }" "$DOCS/context.md" 2>/dev/null || \
  sed -i "/$STATS_MARKER/,/^## [^C]/{ /$STATS_MARKER/d; /^## [^C]/!d; }" "$DOCS/context.md" 2>/dev/null
fi

cat >> "$DOCS/context.md" << STATS

$STATS_MARKER

| Metric | Value |
|--------|-------|
| Components | $COMPONENT_COUNT .tsx files |
| Hooks | $HOOK_COUNT .ts files |
| Total TS/TSX files | $TOTAL_TS_FILES |
| Total lines (TS/TSX) | $TOTAL_LINES |
| Branch | $BRANCH |
| Last commit | $LAST_COMMIT |
| Updated | $(date -u +"%Y-%m-%d %H:%M UTC") |

**App dependencies:** $APP_DEPS
**Server dependencies:** $SERVER_DEPS
STATS

echo "✅ context.md stats updated"

# 3. Update timeline.md with latest commits
echo "📅 Updating timeline.md..."
TIMELINE_DATE=$(date -u +"%Y-%m-%d")
RECENT_COMMITS=$(cd "$REPO_ROOT" && git log --oneline -10 --since="12 hours ago" 2>/dev/null)

if [ -n "$RECENT_COMMITS" ]; then
  cat >> "$DOCS/timeline.md" << TIMELINE

## $TIMELINE_DATE

$RECENT_COMMITS
TIMELINE
  echo "✅ timeline.md updated with recent commits"
else
  echo "⏭️  No recent commits for timeline"
fi

# 4. Update sessions-log.md
echo "📖 Updating sessions-log.md..."
cat >> "$DOCS/sessions-log.md" << SESSION

## $(date -u +"%Y-%m-%d %H:%M UTC") - Auto-update after build

**Last commit:** $LAST_COMMIT
**Files changed:** $(cd "$REPO_ROOT" && git diff --stat HEAD~1 2>/dev/null | tail -1 || echo "unknown")
SESSION
echo "✅ sessions-log.md updated"

echo ""
echo "🎉 All docs updated! Files changed:"
cd "$DOCS" && git diff --stat . 2>/dev/null || ls -lt *.md | head -5

# 5. Update todo.md - scan for TODO/FIXME/HACK in codebase
echo "📋 Updating todo.md..."
TODO_DATE=$(date -u +"%Y-%m-%d")
cat > "$DOCS/todo.md" << TODOHEADER
# Entity Todo

*Auto-generated by update-docs.sh on $TODO_DATE*

## Code TODOs
TODOHEADER

cd "$REPO_ROOT"
grep -rn "TODO\|FIXME\|HACK\|XXX" packages/app/src/ packages/server/src/ packages/db/src/ --include="*.ts" --include="*.tsx" 2>/dev/null | while IFS= read -r line; do
  echo "- \`$line\`" >> "$DOCS/todo.md"
done

# Add outstanding items from git (uncommitted changes)
DIRTY=$(cd "$REPO_ROOT" && git diff --name-only 2>/dev/null)
if [ -n "$DIRTY" ]; then
  cat >> "$DOCS/todo.md" << DIRTYHEADER

## Uncommitted Changes
DIRTYHEADER
  echo "$DIRTY" | while read f; do echo "- \`$f\`" >> "$DOCS/todo.md"; done
fi

echo "✅ todo.md updated"

# 6. Update decisions.md - append recent commit messages that look architectural
echo "🧠 Updating decisions.md..."
RECENT_FEAT=$(cd "$REPO_ROOT" && git log --oneline -20 --since="24 hours ago" --grep="feat\|refactor\|arch\|decision\|breaking" 2>/dev/null)
if [ -n "$RECENT_FEAT" ]; then
  cat >> "$DOCS/decisions.md" << DECISIONS

## $TODO_DATE - Auto-captured from commits

$RECENT_FEAT

*Review and add rationale manually if needed.*
DECISIONS
  echo "✅ decisions.md updated with recent architectural commits"
else
  echo "⏭️  No architectural commits for decisions.md"
fi
